# -*- mode: yaml; -*-
# vi: set ft=yaml:

---
name: stale

on:  # yamllint disable-line rule:truthy
 schedule:
   - cron: '0 6 * * *'

jobs:
  stale:
    name: stale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          days-before-close: 14
          days-before-stale: 180
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: stale
          stale-issue-message: >
            Thank you for your contribution. This issue has been open for 180
            days without activity and so is considered stale. It will be
            automatically closed in 14 days unless you comment or remove the
            "stale" label.
          stale-pr-label: stale
          stale-pr-message: >
            Thank you for your contribution. This pull request has been open for
            180 days without activity and so is considered stale. It will be
            automatically closed in 14 days unless you comment or remove the
            "stale" label.
